title: Lugo Labs
#logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: true
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
